server:
  port: 809

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ztlsir/education.config.file/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:803/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"